name: Multi-Job Python Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: multi-job-workflow
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set Version
        id: set_version
        run: |
          VERSION="beta"
          echo "App version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: multi-job-workflow
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Run Unit Tests
        run: python3 test_app.py

  deploy:
    name: Deploy App
    needs: [build, test]
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.version != 'beta' && success() }}
    steps:
      - name: Simulate Deployment
        run: echo " Deployment successful for version ${{ needs.build.outputs.version }}"
